// Code generated by conductor msggen from geosim_msgs/msg/GeophoneChunk, geosim_msgs/msg/ContactForce. DO NOT EDIT.

package msgs

import (
	"time"

	conductor "conductor.dev/conductor"
)

//ros:type geosim_msgs/msg/ContactForce
type ContactForce struct {
	Header    Header
	ContactId string
	Position  [3]float64
	Force     [3]float64
}

//ros:type geosim_msgs/msg/GeophoneChunk
type GeophoneChunk struct {
	Header       Header
	SampleRateHz float64
	Samples      []float32
	RangeM       float64
}

//ros:type std_msgs/msg/Header
type Header struct {
	Stamp   time.Time
	FrameId string
}

func init() {
	conductor.RegisterMessage[ContactForce]("geosim_msgs/msg/ContactForce",
		"RIHS01_63aba8eae0c57531a1e65aebb7ba6931be814c92b8a09b674f543021ed66b405")
	conductor.RegisterMessage[GeophoneChunk]("geosim_msgs/msg/GeophoneChunk",
		"RIHS01_5b9cb8d92d6adb6d18b22caab85fb56d8713c6024ee910b255dc7dbe755e4223")
	conductor.RegisterMessage[Header]("std_msgs/msg/Header",
		"RIHS01_f49fb3ae2cf070f793645ff749683ac6b06203e41c891e17701b1cb597ce6a01")
}
