// Command geosweep explores the model's parameter space.
//
// Three modes, one parameter space. The ranges live in internal/sweep and are
// used by all of them, because two copies of a parameter range is how a
// sensitivity analysis ends up characterising a model nobody is running.
//
//	geosweep -o sweep.csv                     one axis at a time
//	geosweep -axes axes.json                  what the axes are and why
//	geosweep -design d.csv -o results.csv     evaluate a batch
//
// The one-at-a-time sweep finds the gradient at the reference point and says
// nothing about interactions; that is the honest limitation of it, and the
// reason for the third mode. A Sobol decomposition needs tens of thousands of
// evaluations over the joint space, generated by py/analysis/sobol.py and
// evaluated here — one file each way, and no per-sample boundary between the
// two languages.
package main

import (
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strconv"
	"time"

	"geosim.dev/geosim/internal/config"
	"geosim.dev/geosim/internal/sweep"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "geosweep:", err)
		os.Exit(1)
	}
}

func run() error {
	var (
		out        = flag.String("o", "sweep.csv", "output CSV path")
		axesPath   = flag.String("axes", "", "write the axis definitions as JSON and stop")
		designPath = flag.String("design", "", "evaluate a design CSV instead of sweeping")
	)
	flag.Parse()

	switch {
	case *axesPath != "":
		return writeAxes(*axesPath)
	case *designPath != "":
		return evaluate(*designPath, *out)
	}
	return oneAtATime(*out)
}

// writeAxes publishes the parameter space, so the Python side does not carry a
// second copy of every range.
func writeAxes(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(sweep.Axes()); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %d axes to %s\n", len(sweep.Axes()), path)
	return nil
}

func evaluate(designPath, out string) error {
	in, err := os.Open(designPath)
	if err != nil {
		return err
	}
	defer in.Close()
	d, err := sweep.ReadDesign(in)
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "evaluating %d runs over %d axes\n", len(d.Rows), len(d.Columns))

	start := time.Now()
	m, errs := sweep.Evaluate(d)
	bad := 0
	for _, e := range errs {
		if e != nil {
			bad++
		}
	}
	elapsed := time.Since(start)
	fmt.Fprintf(os.Stderr, "%d runs in %v (%.1f ms each), %d rejected\n",
		len(d.Rows), elapsed.Round(time.Millisecond),
		float64(elapsed.Milliseconds())/float64(len(d.Rows)), bad)
	if bad > 0 {
		fmt.Fprintf(os.Stderr, "rejected rows are written with an error and no metrics; "+
			"a variance decomposition must drop them, not fill them in\n")
	}

	f, err := os.Create(out)
	if err != nil {
		return err
	}
	defer f.Close()
	if err := sweep.WriteResults(f, d, m, errs); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", out)
	return nil
}

func oneAtATime(out string) error {
	f, err := os.Create(out)
	if err != nil {
		return err
	}
	defer f.Close()
	w := csv.NewWriter(f)
	defer w.Flush()

	if err := w.Write([]string{"axis", "unit", "value", "peak_v", "rms_v", "centroid_hz", "snr_db"}); err != nil {
		return err
	}
	base, err := sweep.Measure(config.Default())
	if err != nil {
		return fmt.Errorf("reference run: %w", err)
	}
	fmt.Fprintf(os.Stderr, "reference: peak %.4g V, rms %.4g V, centroid %.1f Hz, %.0f dB\n",
		base.PeakV, base.RMSV, base.CentroidHz, base.SNRdB)

	g := func(v float64) string { return strconv.FormatFloat(v, 'g', 8, 64) }
	for _, a := range sweep.Axes() {
		var loM, hiM sweep.Metrics
		values := a.Values()
		for i, v := range values {
			c := config.Default()
			a.Apply(&c, v)
			m, err := sweep.Measure(c)
			if err != nil {
				fmt.Fprintf(os.Stderr, "%s=%g: %v\n", a.Name, v, err)
				continue
			}
			if i == 0 {
				loM = m
			}
			hiM = m
			if err := w.Write([]string{a.Name, a.Unit, g(v),
				g(m.PeakV), g(m.RMSV), g(m.CentroidHz), g(m.SNRdB)}); err != nil {
				return err
			}
		}
		fmt.Fprintf(os.Stderr, "%-20s %6.3g -> %-6.3g   rms x%.2f   centroid %.0f -> %.0f Hz\n",
			a.Name, values[0], values[len(values)-1],
			hiM.RMSV/loM.RMSV, loM.CentroidHz, hiM.CentroidHz)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", out)
	return nil
}
