"""Run the validations and write the report.

The plan lists V1 to V12 and says the report must be regenerable from one
command. This is that command. It runs the tests each validation names, captures
what they logged, and writes docs/validation-report.md.

    python3 py/analysis/validation_report.py

The numbers in the report come out of `go test -json`, so they are the numbers
the tests actually measured on the run that produced the report. A report whose
figures are typed in beside the tests is a report that will one day disagree
with them, and the disagreement will be invisible: both halves look fine on
their own.

Two things it will not do. It will not mark a validation green because its tests
passed if the validation itself is only partly done — V6 and V9 both carry an
outstanding note in docs/validation.json, and a partial pass is reported as
partial no matter how many tests are green underneath it. And it will not
silently skip a test it cannot find: a renamed test is reported as missing,
because a validation that quietly stops running is worse than one that fails.
"""

import argparse
import json
import pathlib
import subprocess
import sys
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parents[2]


def run_package(pkg, tests, short):
    """Run named tests in one package, returning {test: (status, [log lines])}."""
    pattern = "^(" + "|".join(tests) + ")$"
    cmd = ["go", "test", "-json", "-count=1", "-run", pattern, pkg]
    if short:
        cmd.insert(2, "-short")
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)

    status = {}
    logs = defaultdict(list)
    for line in proc.stdout.splitlines():
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            continue
        name = ev.get("Test")
        if not name:
            continue
        # Subtests report under "Parent/child"; their output belongs to the parent.
        top = name.split("/")[0]
        if ev["Action"] in ("pass", "fail", "skip"):
            if name == top:
                status[top] = ev["Action"]
        elif ev["Action"] == "output":
            text = ev.get("Output", "").rstrip("\n")
            stripped = text.strip()
            if not stripped or stripped.startswith(("=== RUN", "=== PAUSE", "=== CONT", "--- PASS", "--- FAIL", "--- SKIP")):
                continue
            logs[top].append(stripped)
    if proc.returncode != 0 and not status:
        # A build failure produces no test events at all, and reporting that as
        # "missing tests" would be misleading.
        return None, proc.stderr.strip() or proc.stdout.strip()
    return {t: (status.get(t), logs.get(t, [])) for t in tests}, None


def collect(doc, short):
    results = []
    for v in doc["validations"]:
        groups = [(v["package"], v["tests"])] + [
            (a["package"], a["tests"]) for a in v.get("also", [])
        ]
        entry = {"v": v, "groups": [], "pass": 0, "fail": 0, "skip": 0, "missing": 0}
        for pkg, tests in groups:
            got, err = run_package(pkg, tests, short)
            if got is None:
                entry["groups"].append((pkg, None, err))
                entry["fail"] += len(tests)
                continue
            rows = []
            for t in tests:
                st, logs = got[t]
                if st is None:
                    entry["missing"] += 1
                    st = "missing"
                else:
                    entry[st] = entry.get(st, 0) + 1
                rows.append((t, st, logs))
            entry["groups"].append((pkg, rows, None))
        results.append(entry)
        print(
            f"  {v['id']:<4} {entry['pass']} passed, {entry['fail']} failed, "
            f"{entry['skip']} skipped, {entry['missing']} missing",
            file=sys.stderr,
        )
    return results


def verdict(e):
    if e["missing"]:
        return "MISSING", "a test named here no longer exists"
    if e["fail"]:
        return "FAIL", ""
    if e["v"].get("outstanding"):
        return "PARTIAL", e["v"]["outstanding"]
    if e["skip"] and not e["pass"]:
        return "SKIPPED", "every test was skipped; run without -short"
    if e["skip"]:
        return "PASS*", "some tests were skipped; run without -short for the full set"
    return "PASS", ""


BADGE = {
    "PASS": "green",
    "PASS*": "green, partly skipped",
    "PARTIAL": "**partial**",
    "SKIPPED": "**not run**",
    "FAIL": "**FAILED**",
    "MISSING": "**MISSING**",
}


def write(results, out, short):
    lines = []
    lines.append("# WP1 validation report\n")
    lines.append(
        "Generated by `python3 py/analysis/validation_report.py`. Every figure below "
        "is captured from the test that measured it on this run, so the report cannot "
        "drift from the suite. The mapping from validation to test lives in "
        "[validation.json](validation.json); the validations themselves are defined in "
        "[wp1-forward-model-plan.md](wp1-forward-model-plan.md).\n"
    )
    if short:
        lines.append(
            "> Run with `-short`. The grid comparisons of V5 take minutes and are "
            "skipped, so V5 is reported as partly skipped rather than green.\n"
        )

    lines.append("## Summary\n")
    lines.append("| | validation | status | |")
    lines.append("|---|---|---|---|")
    for e in results:
        v, (st, why) = e["v"], verdict(e)
        lines.append(f"| {v['id']} | {v['target']} | {BADGE[st]} | {why} |")
    lines.append("")

    lines.append("## Detail\n")
    for e in results:
        v, (st, why) = e["v"], verdict(e)
        lines.append(f"### {v['id']} — {v['target']}\n")
        lines.append(f"**Oracle.** {v['oracle']}\n")
        lines.append(f"**Status.** {BADGE[st]}. {why}\n" if why else f"**Status.** {BADGE[st]}\n")
        for pkg, rows, err in e["groups"]:
            lines.append(f"`{pkg}`\n")
            if rows is None:
                lines.append("```\n" + (err or "the package did not build") + "\n```\n")
                continue
            for t, status, logs in rows:
                mark = {"pass": "ok", "fail": "FAILED", "skip": "skipped", "missing": "MISSING"}[status]
                lines.append(f"- `{t}` — {mark}")
                if logs:
                    lines.append("")
                    lines.append("  ```")
                    for line in logs:
                        lines.append("  " + line)
                    lines.append("  ```")
            lines.append("")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("-m", "--map", default=str(ROOT / "docs" / "validation.json"))
    ap.add_argument("-o", "--out", default=str(ROOT / "docs" / "validation-report.md"))
    ap.add_argument(
        "--short", action="store_true", help="pass -short to go test; V5's grid runs are skipped"
    )
    args = ap.parse_args()

    doc = json.loads(pathlib.Path(args.map).read_text())
    print(f"{len(doc['validations'])} validations", file=sys.stderr)
    results = collect(doc, args.short)
    write(results, pathlib.Path(args.out), args.short)

    bad = [e["v"]["id"] for e in results if verdict(e)[0] in ("FAIL", "MISSING", "SKIPPED")]
    if bad:
        print("not green: " + ", ".join(bad), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
